version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./web:/web
  
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./web:/web

  